### PR TITLE
Add publish script

### PR DESCRIPTION
**Pull request by latentflip**

### CODE REVIEW

**Comment by latentflip** [comment]
This should allow @cdaringe to publish himself when he merges #7 as long as he pulls this stuff in.

**Comment by latentflip** [comment]
There's also this: https://github.com/boennemann/semantic-release

**Comment by wraithgar** [comment]
:shipit: @cdaringe can you merge this and try to `npm run publish-major` (this is going to be a major right?)

**Comment by wraithgar** [comment]
@latentflip can you add `gar` `andyet` and whatever @cdaringe's username is on npm to this package on npm?

**Comment by latentflip** [comment]
@wraithgar @cdaringe added

**Comment by cdaringe** [comment]
fire in the hole!  worked great

**Pull request merged**
